/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "../../common.js"
  

  export interface MockGridOracleInterface extends Interface {
    getFunction(nameOrSignature: "factorBps" | "setFactorBps"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "FactorUpdated"): EventFragment;

    encodeFunctionData(functionFragment: 'factorBps', values?: undefined): string;
encodeFunctionData(functionFragment: 'setFactorBps', values: [BigNumberish]): string;

    decodeFunctionResult(functionFragment: 'factorBps', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setFactorBps', data: BytesLike): Result;
  }

  
    export namespace FactorUpdatedEvent {
      export type InputTuple = [oldFactorBps: BigNumberish, newFactorBps: BigNumberish];
      export type OutputTuple = [oldFactorBps: bigint, newFactorBps: bigint];
      export interface OutputObject {oldFactorBps: bigint, newFactorBps: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface MockGridOracle extends BaseContract {
    
    connect(runner?: ContractRunner | null): MockGridOracle;
    waitForDeployment(): Promise<this>;

    interface: MockGridOracleInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    factorBps: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    setFactorBps: TypedContractMethod<
      [_factorBps: BigNumberish, ],
      [void],
      'nonpayable'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'factorBps'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'setFactorBps'): TypedContractMethod<
      [_factorBps: BigNumberish, ],
      [void],
      'nonpayable'
    >;

    getEvent(key: 'FactorUpdated'): TypedContractEvent<FactorUpdatedEvent.InputTuple, FactorUpdatedEvent.OutputTuple, FactorUpdatedEvent.OutputObject>;

    filters: {
      
      'FactorUpdated(uint256,uint256)': TypedContractEvent<FactorUpdatedEvent.InputTuple, FactorUpdatedEvent.OutputTuple, FactorUpdatedEvent.OutputObject>;
      FactorUpdated: TypedContractEvent<FactorUpdatedEvent.InputTuple, FactorUpdatedEvent.OutputTuple, FactorUpdatedEvent.OutputObject>;
    
    };
  }