/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as greenRecsRegistrySol from './GreenRecsRegistry.sol/index.js';
export { CarbonCredits1155__factory } from './CarbonCredits1155__factory.js';