/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

  import { Contract, Interface, type ContractRunner } from "ethers";
  import type { ICarbonCredits1155, ICarbonCredits1155Interface } from "../../../registry/GreenRecsRegistry.sol/ICarbonCredits1155.js";

  const _abi = [
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "to",
        "type": "address"
      },
      {
        "internalType": "uint256",
        "name": "amount",
        "type": "uint256"
      }
    ],
    "name": "mintFromRecIssue",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  }
] as const;

  export class ICarbonCredits1155__factory {
    static readonly abi = _abi;
    static createInterface(): ICarbonCredits1155Interface {
      return new Interface(_abi) as ICarbonCredits1155Interface;
    }
    static connect(address: string, runner?: ContractRunner | null): ICarbonCredits1155 {
      return new Contract(address, _abi, runner) as unknown as ICarbonCredits1155;
    }
  }
  