/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { GreenRecsRegistry__factory } from './GreenRecsRegistry__factory.js';
export { ICarbonCredits1155__factory } from './ICarbonCredits1155__factory.js';