/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { Addressable } from "ethers";
import { Contract, ContractFactory, ContractTransactionResponse, Interface } from "ethers"
import type { Signer, BigNumberish, ContractDeployTransaction, ContractRunner } from "ethers"
import type { NonPayableOverrides } from "../../../common.js"
  import type { MockGridOracle, MockGridOracleInterface } from "../../../market/mocks/MockGridOracle.js";

  const _abi = [
  {
    "inputs": [
      {
        "internalType": "uint256",
        "name": "_factorBps",
        "type": "uint256"
      }
    ],
    "stateMutability": "nonpayable",
    "type": "constructor"
  },
  {
    "inputs": [],
    "name": "InvalidFactor",
    "type": "error"
  },
  {
    "anonymous": false,
    "inputs": [
      {
        "indexed": false,
        "internalType": "uint256",
        "name": "oldFactorBps",
        "type": "uint256"
      },
      {
        "indexed": false,
        "internalType": "uint256",
        "name": "newFactorBps",
        "type": "uint256"
      }
    ],
    "name": "FactorUpdated",
    "type": "event"
  },
  {
    "inputs": [],
    "name": "factorBps",
    "outputs": [
      {
        "internalType": "uint256",
        "name": "",
        "type": "uint256"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "uint256",
        "name": "_factorBps",
        "type": "uint256"
      }
    ],
    "name": "setFactorBps",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  }
] as const;

  const _bytecode = "0x6080604052348015600e575f5ffd5b506040516102cf3803806102cf8339818101604052810190602e919060b2565b6103e8811080603f5750620186a081115b156075576040517f3fb86fe200000000000000000000000000000000000000000000000000000000815260040160405180910390fd5b805f819055505060d8565b5f5ffd5b5f819050919050565b6094816084565b8114609d575f5ffd5b50565b5f8151905060ac81608d565b92915050565b5f6020828403121560c45760c36080565b5b5f60cf8482850160a0565b91505092915050565b6101ea806100e55f395ff3fe608060405234801561000f575f5ffd5b5060043610610034575f3560e01c806348d8031f14610038578063adf0d61314610054575b5f5ffd5b610052600480360381019061004d919061013a565b610072565b005b61005c6100fe565b6040516100699190610174565b60405180910390f35b6103e88110806100845750620186a081115b156100bb576040517f3fb86fe200000000000000000000000000000000000000000000000000000000815260040160405180910390fd5b7f4560f5b8017b11ba6b4f6b45b5f948807cf3936aa30ed7d2a6ed72d170a05b4a5f54826040516100ed92919061018d565b60405180910390a1805f8190555050565b5f5481565b5f5ffd5b5f819050919050565b61011981610107565b8114610123575f5ffd5b50565b5f8135905061013481610110565b92915050565b5f6020828403121561014f5761014e610103565b5b5f61015c84828501610126565b91505092915050565b61016e81610107565b82525050565b5f6020820190506101875f830184610165565b92915050565b5f6040820190506101a05f830185610165565b6101ad6020830184610165565b939250505056fea2646970667358221220c5807e967cfbca350e748ab7753eddacffeb5b2e6c69ec33f4a5d6ee30ac69ee64736f6c634300081c0033";

  
      type MockGridOracleConstructorParams = [signer?: Signer] | ConstructorParameters<typeof ContractFactory>;

      const isSuperArgs = (xs: MockGridOracleConstructorParams): xs is ConstructorParameters<typeof ContractFactory> =>
        xs.length > 1
    

  export class MockGridOracle__factory extends ContractFactory {
    
      constructor(...args: MockGridOracleConstructorParams) {
        if (isSuperArgs(args)) {
          super(...args);
        } else {
          super(_abi, _bytecode, args[0]);
        }
        
      }
    
    override getDeployTransaction(_factorBps: BigNumberish, overrides?: NonPayableOverrides & { from?: string }): Promise<ContractDeployTransaction> {
      return super.getDeployTransaction(_factorBps, overrides || {});
    };
    override deploy(_factorBps: BigNumberish, overrides?: NonPayableOverrides & { from?: string }) {
      return super.deploy(_factorBps, overrides || {}) as Promise<MockGridOracle & {
        deploymentTransaction(): ContractTransactionResponse;
      }>;
    }
    override connect(runner: ContractRunner | null): MockGridOracle__factory {
      return super.connect(runner) as MockGridOracle__factory;
    }
    
    
    static readonly bytecode = _bytecode;
    static readonly abi = _abi;
    static createInterface(): MockGridOracleInterface {
      return new Interface(_abi) as MockGridOracleInterface;
    }
    
    override attach(address: string | Addressable): MockGridOracle {
      return super.attach(address) as MockGridOracle;
    }
  static connect(address: string, runner?: ContractRunner | null): MockGridOracle {
      return new Contract(address, _abi, runner) as unknown as MockGridOracle;
    }
  }

  
  