/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "../common.js"
  
export declare namespace GridFlexMarket {
      
    export type SlotStruct = {producer: AddressLike, consumer: AddressLike, startTime: BigNumberish, endTime: BigNumberish, energyWh: BigNumberish, pricePerWhWei: BigNumberish, status: BigNumberish}

    export type SlotStructOutput = [producer: string, consumer: string, startTime: bigint, endTime: bigint, energyWh: bigint, pricePerWhWei: bigint, status: bigint] & {producer: string, consumer: string, startTime: bigint, endTime: bigint, energyWh: bigint, pricePerWhWei: bigint, status: bigint }
  
    }

  export interface GridFlexMarketInterface extends Interface {
    getFunction(nameOrSignature: "cancelSlot" | "createSlot" | "getSlot" | "matchSlot" | "nextSlotId" | "oracle" | "quoteMatch"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "SlotCancelled" | "SlotCreated" | "SlotMatched"): EventFragment;

    encodeFunctionData(functionFragment: 'cancelSlot', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'createSlot', values: [BigNumberish, BigNumberish, BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'getSlot', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'matchSlot', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'nextSlotId', values?: undefined): string;
encodeFunctionData(functionFragment: 'oracle', values?: undefined): string;
encodeFunctionData(functionFragment: 'quoteMatch', values: [BigNumberish]): string;

    decodeFunctionResult(functionFragment: 'cancelSlot', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'createSlot', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getSlot', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'matchSlot', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'nextSlotId', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'oracle', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'quoteMatch', data: BytesLike): Result;
  }

  
    export namespace SlotCancelledEvent {
      export type InputTuple = [slotId: BigNumberish, producer: AddressLike];
      export type OutputTuple = [slotId: bigint, producer: string];
      export interface OutputObject {slotId: bigint, producer: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace SlotCreatedEvent {
      export type InputTuple = [slotId: BigNumberish, producer: AddressLike, startTime: BigNumberish, endTime: BigNumberish, energyWh: BigNumberish, pricePerWhWei: BigNumberish];
      export type OutputTuple = [slotId: bigint, producer: string, startTime: bigint, endTime: bigint, energyWh: bigint, pricePerWhWei: bigint];
      export interface OutputObject {slotId: bigint, producer: string, startTime: bigint, endTime: bigint, energyWh: bigint, pricePerWhWei: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace SlotMatchedEvent {
      export type InputTuple = [slotId: BigNumberish, producer: AddressLike, consumer: AddressLike, paidWei: BigNumberish, oracleFactorBps: BigNumberish];
      export type OutputTuple = [slotId: bigint, producer: string, consumer: string, paidWei: bigint, oracleFactorBps: bigint];
      export interface OutputObject {slotId: bigint, producer: string, consumer: string, paidWei: bigint, oracleFactorBps: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface GridFlexMarket extends BaseContract {
    
    connect(runner?: ContractRunner | null): GridFlexMarket;
    waitForDeployment(): Promise<this>;

    interface: GridFlexMarketInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    cancelSlot: TypedContractMethod<
      [slotId: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    createSlot: TypedContractMethod<
      [startTime: BigNumberish, endTime: BigNumberish, energyWh: BigNumberish, pricePerWhWei: BigNumberish, ],
      [bigint],
      'nonpayable'
    >
    

    
    getSlot: TypedContractMethod<
      [slotId: BigNumberish, ],
      [GridFlexMarket.SlotStructOutput],
      'view'
    >
    

    
    matchSlot: TypedContractMethod<
      [slotId: BigNumberish, ],
      [void],
      'payable'
    >
    

    
    nextSlotId: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    oracle: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    quoteMatch: TypedContractMethod<
      [slotId: BigNumberish, ],
      [[bigint, bigint] & {totalWei: bigint, factorBps: bigint }],
      'view'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'cancelSlot'): TypedContractMethod<
      [slotId: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'createSlot'): TypedContractMethod<
      [startTime: BigNumberish, endTime: BigNumberish, energyWh: BigNumberish, pricePerWhWei: BigNumberish, ],
      [bigint],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'getSlot'): TypedContractMethod<
      [slotId: BigNumberish, ],
      [GridFlexMarket.SlotStructOutput],
      'view'
    >;
getFunction(nameOrSignature: 'matchSlot'): TypedContractMethod<
      [slotId: BigNumberish, ],
      [void],
      'payable'
    >;
getFunction(nameOrSignature: 'nextSlotId'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'oracle'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'quoteMatch'): TypedContractMethod<
      [slotId: BigNumberish, ],
      [[bigint, bigint] & {totalWei: bigint, factorBps: bigint }],
      'view'
    >;

    getEvent(key: 'SlotCancelled'): TypedContractEvent<SlotCancelledEvent.InputTuple, SlotCancelledEvent.OutputTuple, SlotCancelledEvent.OutputObject>;
getEvent(key: 'SlotCreated'): TypedContractEvent<SlotCreatedEvent.InputTuple, SlotCreatedEvent.OutputTuple, SlotCreatedEvent.OutputObject>;
getEvent(key: 'SlotMatched'): TypedContractEvent<SlotMatchedEvent.InputTuple, SlotMatchedEvent.OutputTuple, SlotMatchedEvent.OutputObject>;

    filters: {
      
      'SlotCancelled(uint256,address)': TypedContractEvent<SlotCancelledEvent.InputTuple, SlotCancelledEvent.OutputTuple, SlotCancelledEvent.OutputObject>;
      SlotCancelled: TypedContractEvent<SlotCancelledEvent.InputTuple, SlotCancelledEvent.OutputTuple, SlotCancelledEvent.OutputObject>;
    

      'SlotCreated(uint256,address,uint40,uint40,uint128,uint128)': TypedContractEvent<SlotCreatedEvent.InputTuple, SlotCreatedEvent.OutputTuple, SlotCreatedEvent.OutputObject>;
      SlotCreated: TypedContractEvent<SlotCreatedEvent.InputTuple, SlotCreatedEvent.OutputTuple, SlotCreatedEvent.OutputObject>;
    

      'SlotMatched(uint256,address,address,uint256,uint256)': TypedContractEvent<SlotMatchedEvent.InputTuple, SlotMatchedEvent.OutputTuple, SlotMatchedEvent.OutputObject>;
      SlotMatched: TypedContractEvent<SlotMatchedEvent.InputTuple, SlotMatchedEvent.OutputTuple, SlotMatchedEvent.OutputObject>;
    
    };
  }