/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as greenVaultMvpSol from './GreenVault_MVP.sol/index.js';
export type { greenVaultMvpSol };
import type * as mocks from './mocks/index.js';
export type { mocks };