/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { GreenRecsRegistry } from './GreenRecsRegistry.js';
export type { ICarbonCredits1155 } from './ICarbonCredits1155.js';