/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as greenRecsRegistrySol from './GreenRecsRegistry.sol/index.js';
export type { greenRecsRegistrySol };
export type { CarbonCredits1155 } from './CarbonCredits1155.js';