/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */


import { ethers } from 'ethers'
import { DeployContractOptions, FactoryOptions, HardhatEthersHelpers as HardhatEthersHelpersBase} from "@nomicfoundation/hardhat-ethers/types";

import * as Contracts from "./index.js";

declare module "@nomicfoundation/hardhat-ethers/types" {
  interface HardhatEthersHelpers extends HardhatEthersHelpersBase {
  getContractFactory(name: 'EnergyGovernanceDAO', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.EnergyGovernanceDAO__factory>
getContractFactory(name: 'GridFlexMarket', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.GridFlexMarket__factory>
getContractFactory(name: 'MockGridOracle', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.MockGridOracle__factory>
getContractFactory(name: 'GreenRecsRegistry', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.GreenRecsRegistry__factory>
getContractFactory(name: 'GreenVaultSimple', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.GreenVaultSimple__factory>
getContractFactory(name: 'MockUSDC', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.MockUSDC__factory>

  getContractAt(name: 'EnergyGovernanceDAO', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.EnergyGovernanceDAO>
getContractAt(name: 'GridFlexMarket', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.GridFlexMarket>
getContractAt(name: 'MockGridOracle', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.MockGridOracle>
getContractAt(name: 'GreenRecsRegistry', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.GreenRecsRegistry>
getContractAt(name: 'GreenVaultSimple', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.GreenVaultSimple>
getContractAt(name: 'MockUSDC', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.MockUSDC>

  deployContract(name: 'EnergyGovernanceDAO', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.EnergyGovernanceDAO>
deployContract(name: 'GridFlexMarket', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.GridFlexMarket>
deployContract(name: 'MockGridOracle', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.MockGridOracle>
deployContract(name: 'GreenRecsRegistry', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.GreenRecsRegistry>
deployContract(name: 'GreenVaultSimple', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.GreenVaultSimple>
deployContract(name: 'MockUSDC', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.MockUSDC>

  deployContract(name: 'EnergyGovernanceDAO', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.EnergyGovernanceDAO>
deployContract(name: 'GridFlexMarket', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.GridFlexMarket>
deployContract(name: 'MockGridOracle', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.MockGridOracle>
deployContract(name: 'GreenRecsRegistry', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.GreenRecsRegistry>
deployContract(name: 'GreenVaultSimple', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.GreenVaultSimple>
deployContract(name: 'MockUSDC', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.MockUSDC>

    // default types
    getContractFactory(
      name: string,
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<ethers.ContractFactory>;
    getContractFactory(
      abi: any[],
      bytecode: ethers.BytesLike,
      signer?: ethers.Signer
    ): Promise<ethers.ContractFactory>;
    getContractAt(
      nameOrAbi: string | any[],
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<ethers.Contract>;
    deployContract(
      name: string,
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<ethers.Contract>;
    deployContract(
      name: string,
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<ethers.Contract>;
  }
}
  